fails:Hash#rehash causes a RuntimeError to be raised if called inside an iterator block
fails:Hash#rehash raises a RuntimeError if called on a frozen instance
